#pragma once

namespace dune3d {

enum class InToolActionID {
    NONE,
    // common
    LMB,
    RMB,
    TOGGLE_CONSTRUCTION,
    TOGGLE_COINCIDENT_CONSTRAINT,
    TOGGLE_HV_CONSTRAINT,
    TOGGLE_TANGENT_CONSTRAINT,
    ROTATE_X,
    ROTATE_Y,
    ROTATE_Z,
    TOGGLE_LOCK_ROTATION_CONSTRAINT,

    FLIP_ARC,
    ARC_MODE,

    TOGGLE_ARC,
    TOGGLE_BEZIER,

    CLEAR_EDGES,

    CLEAR_SPINE_ENTITIES,

    N_SIDES_INC,
    N_SIDES_DEC,
    ENTER_N_SIDES,

    TOGGLE_RECTANGLE_MODE,
    TOGGLE_RECTANGLE_SQUARE,
    TOGGLE_RECTANGLE_ROUNDED,
    RECTANGLE_CORNER_RADIUS_INC,
    RECTANGLE_CORNER_RADIUS_DEC,
    TOGGLE_CIRCLE_OVAL,
    TOGGLE_CIRCLE_SLICE,
    CIRCLE_SPAN_INC,
    CIRCLE_SPAN_DEC,
    TOGGLE_TEXT_BOLD,
    TOGGLE_TEXT_ITALIC,
    TOGGLE_POLYGON_ROUNDED,
    POLYGON_CORNER_RADIUS_INC,
    POLYGON_CORNER_RADIUS_DEC,

    TOLERANCE_INC,
    TOLERANCE_DEC,
    ENTER_TOLERANCE,

    TOGGLE_AUTO_NORMAL,

    CANCEL,
    COMMIT
};

} // namespace dune3d
